import type { Plugin } from 'vite'
import { readFileSync, existsSync } from 'fs'
import { resolve } from 'path'

/**
 * Vite plugin to embed client manifest into server build
 * This allows the server to resolve hashed client bundle paths at runtime
 */
export function embedManifest(): Plugin {
  return {
    name: 'embed-manifest',
    apply: 'build',
    config(config, { mode }) {
      // Only apply to server build
      if (mode !== 'server') return
    },
    transform(code, id) {
      // Only transform the main server entry
      if (!id.includes('src/index.tsx')) return
      
      // Read the client manifest generated by the client build
      const manifestPath = resolve(__dirname, 'dist/static/.vite/manifest.json')
      
      if (!existsSync(manifestPath)) {
        console.warn('[embed-manifest] Client manifest not found, skipping')
        return
      }
      
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))
      
      // Inject manifest as a constant at the top of the file
      const injection = `
const __CLIENT_MANIFEST__ = ${JSON.stringify(manifest)};
`
      
      return {
        code: injection + code,
        map: null
      }
    }
  }
}
